### ISSUE TITLE
Make tests less reachy-inny and more tappy-aroundy

### ISSUE THREAD

**Issue by misterfifths** [learn-co-curriculum/objc-BlackJackViews#4]
e.g., probably shouldn't directly assign to `hand` property, for instance -- that's not a thing the user can do and probably violates assumptions the student made.
(make sure we also test the case of playing one game, and then going on to another)

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by TOMalley104** [comment]
deadline: Friday 9/4

**Comment by jmburges** [comment]
ok @TOMalley104 I think the biggest change that needs to happen is to explain the importance of the `hand` property and the `updateUI` method. If we do that, then I think this will be fine :)

**Comment by jmburges** [comment]
Closed with PR #6
